name: 3. Execute shell script in the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Welcome Message
        run: |
          echo "Welcome to my second GitHub Actions workflow!"
          date
      - name: Execute shell script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh
      - name: Read file and display content
        run: |
          ls -ltra
          if [ -f "dragon.txt" ]; then
            cat dragon.txt
          else
            echo "dragon.txt does not exist."
          fi