name: 4. Run multiple Jobs in single workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Build Project
              run: echo "Building the project..."
    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Run Tests
              run: echo "Running tests..."
    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Deploy Application
              run: echo "Deploying the application..."
    notify:
        runs-on: ubuntu-latest
        needs: deploy
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Notify Completion
              run: echo "All jobs completed successfully!"
    cleanup:
        runs-on: ubuntu-latest
        needs: [build, test, deploy, notify]
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Cleanup Resources
              run: echo "Cleaning up resources..."
    report:
        runs-on: ubuntu-latest
        needs: cleanup
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Generate Report
              run: echo "Generating report of the workflow execution..."
