name: 7. Event Triggered Workflows
# This workflow is triggered by push or pull request events on the main branch.
on:
  schedule:
    - cron: '*/1 * * * *' # Runs every minute
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Welcome Message
        run: |
          echo "Welcome to my second GitHub Actions workflow!"
          date
      - name: Generate ASCII Artwork using cowsay
        run: |
          sudo apt-get update
          sudo apt-get install -y cowsay
          echo "Generating ASCII art using cowsay..."
          cowsay -f dragon "Run for your life, it's a dragon!" >> dragon.txt
      - name: Read file and display content
        run: |
          ls -ltra
          if [ -f "dragon.txt" ]; then
            cat dragon.txt
          else
            echo "dragon.txt does not exist."
          fi